apiVersion: v1
kind: Pod
metadata:
  annotations:
    bind-mount-options: /mnt/w/projects/itmo/pyweb2024/pod-demo/html:z
  creationTimestamp: "2024-11-13T21:00:18Z"
  labels:
    app: mypod
  name: mypod
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:latest
    name: myapp
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: mnt-w-projects-itmo-pyweb2024-pod-demo-html-host-0
  - command:
    - ./time.sh
    image: registry.access.redhat.com/ubi8:latest
    name: time
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: mnt-w-projects-itmo-pyweb2024-pod-demo-html-host-0
    workingDir: /usr/share/nginx/html
  volumes:
  - hostPath:
      path: /mnt/w/projects/itmo/pyweb2024/pod-demo/html
      type: Directory
    name: mnt-w-projects-itmo-pyweb2024-pod-demo-html-host-0
